<?php

/**
 * IBAN API
 * An API to perform operations on IBAN and SWIFT/BIC numbers. This source of this document is an OpenAPI 3 document which lives at https://github.com/theAPIfox/ibanfox
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@ibanfox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class IbansApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation getIbansIban
     *
     * Get details for an IBAN.
     *
     * @param string $iban  (required)
     *
     * @return Http response
     */
    public function getIbansIban($iban)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getIbansIban as a get method ?');
    }
    /**
     * Operation validateIBAN
     *
     * Validate an IBAN.
     *
     * @param string $iban A candidate IBAN to validate (required)
     *
     * @return Http response
     */
    public function validateIBAN($iban)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing validateIBAN as a get method ?');
    }
}
